### PR TITLE
feat: add a PVC for the worker's data directory

### PR DESCRIPTION
**Pull request by matthieu-foucault**

### CODE REVIEW

**Comment by wenzowski** [comment]
This might have failed because our new trident provisioner has an external finalizer? Trying to re-run this job to see if it failed because it didn't wait for the pv to be provisioned for the pvc before continuing.
Screen Shot 2020-05-29 at 12 34 09 PM
Screen Shot 2020-05-29 at 12 33 42 PM

**Comment by wenzowski** [comment]
oh! it's missing a `volumes` block

**Comment by wenzowski** [comment]
@dleard the `volumeMounts` need to be defined as `volumes` claims for the deployment.
https://docs.openshift.com/container-platform/3.11/dev_guide/persistent_volumes.html#persistent-volumes-claims-as-volumes-in-pods

**Comment by matthieu-foucault** [comment]
Fixed in #74

**Pull request merged**
